### ISSUE TITLE
Able to allow the shop manager user role to edit the prices for all the user role.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/price-by-user-roles-woocommerce#6]
Able to allow the shop manager user role to edit the prices for all the added user role just same like admin user role is able to do it.

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/8889

The enhancement is already done for pro plugin: https://github.com/TycheSoftwares/price-by-user-role-for-woocommerce-pro/commit/2e45ca66fce86a8ed7b6ec03a85a5830465eebfd

**Comment by kenil802** [comment]
One more client has faced the same issue.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/23946
